// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrionApp.Data;

#nullable disable

namespace OrionApp.Migrations
{
    [DbContext(typeof(OrionAppDbContext))]
    [Migration("20250704163036_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("OrionApp.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchContact")
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchManager")
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchPhone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("OrionApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("CatName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("OrionApp.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustDocNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustDocType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustLastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustState")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustZipCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OrionApp.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptManager")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("OrionApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpDepartment")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpDocNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpDocType")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpHireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpLastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpPosition")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpSalary")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpState")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpSupervisor")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpZipCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("OrionApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProdBrand")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdMeasurementUnit")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdPartNum")
                        .HasColumnType("TEXT");

                    b.Property<double>("ProdPriceRetail")
                        .HasColumnType("REAL");

                    b.Property<double>("ProdPriceUnit")
                        .HasColumnType("REAL");

                    b.Property<double>("ProdPriceWholesale")
                        .HasColumnType("REAL");

                    b.Property<string>("ProdSerialNum")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OrionApp.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TotalAmount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("OrionApp.Models.PurchaseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PurchaseDetails");
                });

            modelBuilder.Entity("OrionApp.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillingAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DiscountAmount")
                        .HasColumnType("REAL");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaleStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingCompany")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ShippingCost")
                        .HasColumnType("REAL");

                    b.Property<string>("ShippingMethod")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SubTotalAmount")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("OrionApp.Models.SaleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Discount")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SaleDetails");
                });

            modelBuilder.Entity("OrionApp.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoreContact")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreManager")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorePhone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("OrionApp.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupContactEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupContactPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupMainPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupPaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupState")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupWebsite")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupZipCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
